# Generated by Django 5.2.7 on 2025-10-07 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True)),
                ('summary', models.TextField()),
                ('imgUrl', models.URLField(default='https://img.daisyui.com/images/stock/photo-1606107557195-0e29a4b5b4aa.webp')),
            ],
        ),
    ]
