# Generated by Django 5.2.7 on 2025-10-07 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='課程標題')),
                ('scenario', models.TextField(verbose_name='情境描述 (為什麼要學)')),
                ('introduction', models.TextField(blank=True, verbose_name='功能介紹')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '單元課程',
                'verbose_name_plural': '單元課程',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField(verbose_name='步驟序號')),
                ('description', models.TextField(verbose_name='步驟說明')),
                ('image', models.ImageField(blank=True, null=True, upload_to='steps/', verbose_name='步驟圖示')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='courses.lesson', verbose_name='所屬課程')),
            ],
            options={
                'verbose_name': '操作步驟',
                'verbose_name_plural': '操作步驟',
                'ordering': ['step_number'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='主題標題')),
                ('icon', models.CharField(blank=True, max_length=10, verbose_name='主題圖示 (Emoji)')),
                ('description', models.TextField(verbose_name='主題引導語')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '教學主題',
                'verbose_name_plural': '教學主題',
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.AddField(
            model_name='lesson',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.topic', verbose_name='所屬主題'),
        ),
    ]
